
#ifndef MIDI_H
#define MIDI_H

#include "stm32f4xx_hal.h"
#include "stdbool.h"

#define MIDI_CHANNEL				0

#define MIDI_BUFFER_LENGTH           256
#define MIDI_MAX_CHANNELS_NUM        16
#define MIDI_MAX_CABLES_NUM          16
#define MIDI_MAX_ADDITIONAL_VELOCITY 127
#define MIDI_MAX_NOTE_SHIFT          24
#define MIDI_MIN_NOTE_SHIFT         -24

#define MIDI_MESSAGE_NOTE_OFF          0x80 | MIDI_CHANNEL
#define MIDI_MESSAGE_NOTE_ON           0x90 | MIDI_CHANNEL
#define MIDI_MESSAGE_KEY_PRESSURE      0xA0 | MIDI_CHANNEL
#define MIDI_MESSAGE_CONTROL_CHANGE    0xB0 | MIDI_CHANNEL
#define MIDI_MESSAGE_PROGRAM_CHANGE    0xC0 | MIDI_CHANNEL
#define MIDI_MESSAGE_CHANNEL_PRESSURE  0xD0 | MIDI_CHANNEL
#define MIDI_MESSAGE_PITCH_BAND_CHANGE 0xE0 | MIDI_CHANNEL

#define MIDI_MESSAGE_TIMING_CLOCK   0xF8
#define MIDI_MESSAGE_START          0xFA
#define MIDI_MESSAGE_CONTINUE       0xFB
#define MIDI_MESSAGE_STOP           0xFC
#define MIDI_MESSAGE_ACTIVE_SENSING 0xFE
#define MIDI_MESSAGE_SYSTEM_RESET   0xFF

#define MIDI_MESSAGE_TIME_CODE_QTR_FRAME 0xF1
#define MIDI_MESSAGE_SONG_POSITION       0xF2
#define MIDI_MESSAGE_SONG_SELECT         0xF3

#define MIDI_MASK_STATUS_BYTE       0x80
#define MIDI_MASK_REAL_TIME_MESSAGE 0xF8

#define MIDI_MESSAGE_CONTROL_ALL_SOUNDS_OFF        120
#define MIDI_MESSAGE_CONTROL_RESET_ALL_CONTROLLERS 121
#define MIDI_MESSAGE_CONTROL_ALL_NOTES_OFF         123

#define MIDI_MESSAGE_PITCH_BAND_MIDDLE 8192
#define MIDI_MESSAGE_PITCH_BAND_MAX    16383
#define MIDI_MESSAGE_PITCH_BAND_MIN    0

#define MIDI_MESSAGE_NOTE_MAX             127
#define MIDI_MESSAGE_NOTE_VOLUME_MAX      127
#define MIDI_MESSAGE_CONTROL_VALUE_MAX    127
#define MIDI_MESSAGE_CONTROL_VALUE_MIN    0
#define MIDI_MESSAGE_CONTROL_VALUE_MIDDLE 64
#define MIDI_MESSAGE_DEFAULT_VOLUME       100

void MIDI_addEventToBuffer(uint8_t message, uint8_t param1, uint8_t param2);
void MIDI_flush();

#endif
